spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    favicon:
      enabled: false
#启用内容版本策略 md5
  resources:
    chain:
      strategy:
        content:
          enabled: true
#应用于版本策略的模式的逗号分隔列表 默认/**
          paths: /css/**,/js/**
  servlet:
    multipart:
      max-file-size: -1 #单个文件的大小 不限制
      max-request-size: -1  #单次请求的文件的总大小 不限制
thymeleaf:
  prefix: classpath:/templates/
  mode: XHTML
  encoding: UTF-8
  content-type: text/html
  cache: false
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.netintech.fixedassets.*.entity
  typeEnumsPackage: com.netintech.fixedassets.*.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
logging:
  config: classpath:logback-spring.xml

#用来暴露 endpoints 的。由于 endpoints 中会包含很多敏感信息，除了 health 和 info 两个支持 web 访问外，其他的默认不支持 web 访问
management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app.name: netintech-shm
  company.name: www.netintech.com
  describe: shm-社会面


